### ISSUE TITLE
Adding totalCount, startCursor, endCursor?

### ISSUE THREAD

**Issue by ryansolid** [Terminal-Systems/apollo-cursor-pagination#7]
Although not necessarily official part of the relay spec it is pretty common to have totalCount on the connection and startCursor, endCursor on the PageInfo.

I do get why in some cases totalCount would be expensive to calculate(especially if you have a huge dataset so you figure out hasNext page by overfetching rather than getting a count) but given the approach used here I don't believe there is any additional overhead?

**Comment by dmerrill6** [comment]
Thanks for your question!

Agree, `totalCount`, `startCursor` and `endCursor` would be very helpful. Will try to add them in the following days, but any help / PR would be very much appreciated.

**Comment by dmerrill6** [comment]
`totalCount` support has been added in PR #8 (release `0.3.0`).

Looking forward to add `startCursor` and `endCursor` ASAP.

**Comment by ryansolid** [comment]
That's great. Thanks for the update.

**Comment by dmerrill6** [comment]
Added `startCursor` and `endCursor` in PR #13 (release 0.4.0).
